Repository radiator-software/p5-net-ssleay, pull requests merged in 2018-09, with the labels that each got.

#48 CI: Travis: test against OpenSSL 1.1.0i, 1.0.2p
  .travis.yml
Labels: ci

#46 Gh 37 add get set security level
  Changes
  SSLeay.xs
  lib/Net/SSLeay.pod
  t/local/65_security_level.t
Labels: enhancement

#53 Set security level to 1 in tests that use pre-generated RSA keys
  Changes
  t/local/07_sslecho.t
  t/local/08_pipe.t
  t/local/36_verify.t
  t/local/64_ticket_sharing.t
Labels: bug

#56 GH-38 Updates to Net::SSLeay::read() and related convenience functions.
  .travis.yml
  Changes
  SSLeay.xs
  lib/Net/SSLeay.pm
  lib/Net/SSLeay.pod
  t/local/07_sslecho.t
  t/local/36_verify.t
Labels: bug, ci, enhancement

#64 GH-63 Add SSL_peek_ex, SSL_read_ex, SSL_write_ex and SSL_has_pending
  Changes
  MANIFEST
  SSLeay.xs
  lib/Net/SSLeay.pod
  t/local/11_read.t
Labels: enhancement

#87 GH-86 Fix set_cert_and_key() return value handling.
  Changes
  lib/Net/SSLeay.pm
Labels: bug

#90 GH-89 Add support for TLSv1.3 via $Net::SSLeay::ssl_version.
  Changes
  lib/Net/SSLeay.pm
  lib/Net/SSLeay.pod
Labels: enhancement

#91 GH-85 Developer release 1.86_06
  Changes
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: dev-release
