Repository radiator-software/p5-net-ssleay, pull requests merged in 2018-07, with the labels that each got.

#18 VMS update for newer SSL versions and removal of Module::Install
  Changes
  Makefile.PL
  README.VMS
Labels: enhancement

#19 GH-17 Updated AppVeyor Perl versions
  .appveyor.yml
Labels: ci

#20 Prevent memory leak in OCSP_cert2ids() and OCSP_response_verify()
  Changes
  SSLeay.xs
Labels: bug

#22 GH-21 Developer release 1.86_04
  Changes
  lib/Net/SSLeay.pm
Labels: dev-release

#24 Sync Net::SSLeay and Net::SSLeay::Handle version numbers
  Changes
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: bug

#27 Re-enable d2i_X509_bio() test for LibreSSL
  Changes
  t/local/33_x509_create_cert.t
Labels: bug
