Repository radiator-software/p5-net-ssleay, pull requests merged in 2021-12, with the labels that each got.

#345 GH-335 Ignore OpenSSL config file for better provider control.
  t/local/22_provider.t
  t/local/22_provider_try_load.t
  t/local/22_provider_try_load_zero_retain.t
Labels: enhancement

#343 GH-316 Remove undefined exportable symbols from SSLeay.pm.
  Changes
  lib/Net/SSLeay.pm
Labels: bug

#347 GH-329 Reorder potential library paths for macOS Monterey compatibility.
  Changes
  Makefile.PL
Labels: enhancement

#349 Developer release 1.91_02
  Changes
  helper_script/generate-test-pki
  helper_script/update-exported-constants
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: dev-release
