Repository radiator-software/p5-net-ssleay, pull requests merged in 2021-01, with the labels that each got.

#239 Replace Travis CI with GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: ci

#244 GitHub Actions: download libssl tarballs from ci-libssl repository
  .github/workflows/ci.yml
Labels: ci

#241 Remove RSAref checks from Makefile.PL
  Changes
  Makefile.PL
  README
Labels: tech-debt

#246 Developer release 1.89_04
  Changes
  helper_script/generate-test-pki
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: dev-release

#247 README.md: replace Travis CI badge with GitHub Actions badge
  README.md
Labels: doc

#248 Makefile.PL: standardise preamble
  Makefile.PL
Labels: enhancement

#250 Clarify libssl version support policy
  Changes
  Makefile.PL
  README
  SSLeay.xs
  TODO
  lib/Net/SSLeay.pod
Labels: doc

#256 Remove references to rt.cpan.org
  CONTRIBUTING.md
  Changes
  Makefile.PL
  README
  helper_script/generate-test-pki
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pod
  lib/Net/SSLeay/Handle.pm
Labels: doc

#258 CONTRIBUTING.md: several minor fixes
  CONTRIBUTING.md
Labels: doc

#260 Developer release 1.89_05
  Changes
  helper_script/generate-test-pki
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: dev-release

#252 Stable release 1.90
  Changes
  helper_script/generate-test-pki
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: stable-release

#261 More pod fixes
  lib/Net/SSLeay.pod
Labels: doc
