Repository radiator-software/p5-net-ssleay, pull requests merged in 2022-01, with the labels that each got.

#351 Test::Net::SSLeay: work around BSD Clangs identifying as GCC
  Changes
  inc/Test/Net/SSLeay.pm
Labels: bug

#353 GH-352 Expose OPENSSL_INFO and related functions, clarify version and library information functions
  Changes
  SSLeay.xs
  constants.c
  helper_script/constants.txt
  lib/Net/SSLeay.pm
  lib/Net/SSLeay.pod
  t/local/03_use.t
  t/local/04_basic.t
  t/local/21_constants.t
Labels: enhancement, doc

#355 Developer release 1.91_03
  Changes
  helper_script/generate-test-pki
  helper_script/update-exported-constants
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: dev-release

#359 Update Net::SSLeay module summary/abstract
  Makefile.PL
  README
  README.md
  lib/Net/SSLeay.pod
Labels: doc
