Repository radiator-software/p5-net-ssleay, pull requests merged in 2022-12, with the labels that each got.

#404 Closes radiator-software/p5-net-ssleay#403
  SSLeay.xs
Labels: bug

#405 Use BIO instead of fp
  SSLeay.xs
Labels: bug, enhancement

#410 RSA_generate_key: declare all variables in PREINIT
  Changes
  SSLeay.xs
Labels: bug

#412 GH-397 SSLeay.pod: Correct CRL revocation reasons P_X509_CRL_add_revoked_serial_hex.
  Changes
  lib/Net/SSLeay.pod
Labels: bug, doc

#414 CI: switch to actions/checkout@v3 in GitHub Actions workflow
  .github/workflows/ci.yml
Labels: ci

#417 CI: add Perl 5.36 to GHA Ubuntu 20.04 matrix
  .github/workflows/ci.yml
Labels: ci

#419 CI: test against OpenSSL 1.1.1s and 3.0.7
  .github/workflows/ci.yml
Labels: ci

#421 Support LibreSSL 3.5 and 3.6
  .github/workflows/ci.yml
  Changes
  README
  lib/Net/SSLeay.pod
Labels: enhancement
