Repository radiator-software/p5-net-ssleay, pull requests merged in 2024-01, with the labels that each got.

#455 GH-454 Makefile.PL, XS and installation fixes
  Changes
  Makefile.PL
  README
  README.OSX
  README.Win32
  SSLeay.xs
Labels: bug, enhancement, tech-debt

#461 Mark Tuure as an inactive contributor
  Makefile.PL
  README
  SSLeay.xs
  helper_script/generate-test-pki
  helper_script/update-exported-constants
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay.pod
  lib/Net/SSLeay/Handle.pm
Labels: doc

#463 Developer release 1.93_04
  Changes
  helper_script/generate-test-pki
  helper_script/update-exported-constants
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: dev-release

#466 Don't automatically detect libssl/libcrypto with ExtUtils::PkgConfig
  Changes
  Makefile.PL
Labels: bug

#468 Developer release 1.93_05
  Changes
  helper_script/generate-test-pki
  helper_script/update-exported-constants
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: dev-release

#470 Stable release 1.94
  Changes
  helper_script/generate-test-pki
  helper_script/update-exported-constants
  inc/Test/Net/SSLeay.pm
  inc/Test/Net/SSLeay/Socket.pm
  lib/Net/SSLeay.pm
  lib/Net/SSLeay/Handle.pm
Labels: stable-release

#472 GH-471 Check that OpenSSL has NPN enabled when testing NPN.
  Changes
  t/local/40_npn_support.t
Labels: bug
