Repository radiator-software/p5-net-ssleay, pull requests merged in 2025-04, with the labels that each got.

#517 CI: run Ubuntu tests on ubuntu-24.04 GitHub Actions runners
  .github/workflows/ci.yml
Labels: ci

#519 GH-518 CI rectification
  .github/workflows/ci.yml
  Changes
Labels: bug, ci

#520 Update tests to pass with OpenSSL 3.4
  Changes
  t/local/32_x509_get_cert_info.t
Labels: enhancement

#522 GH-521 latest libressl and thread test62
  Changes
  SSLeay.xs
  lib/Net/SSLeay.pod
  t/local/32_x509_get_cert_info.t
  t/local/62_threads-ctx_new-deadlock.t
Labels: enhancement
